apiVersion: deployment.vra.jet.crossplane.io/v1alpha1
kind: Deployment
metadata:
  name: sample-deployment-name-1
spec:
  forProvider:
    name: sample-deployment-name-1
    description: "Managed with Crossplane vRA Provider"

    catalogItemId: 41913ba8-068f-389c-b179-747a74df560c
    projectId: 725be285-dcbd-44dc-9416-f5e54aeec294

    inputs:
        input1: test1
        input2: test2

  providerConfigRef:
    name: provider-config-vra-jet-allianz-next