---
apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  name: jet-vra-config
  labels:
    app: crossplane-provider-jet-vra
spec:
  image: ankasoftware/provider-jet-vra-controller:v0.1.2
  replicas: 1
  resources:
    limits:
      cpu: 1000m
      memory: 2048Mi
  args:
    - --max-reconcile-rate=100
    - --debug
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: crossplane-provider-jet-vra
spec:
  package: ankasoftware/provider-jet-vra:v0.1.3
  # packagePullPolicy: Always
  # revisionActivationPolicy: Manual
  revisionHistoryLimit: 1
  controllerConfigRef:
    name: jet-vra-config